In [1]:
import numpy as np

In [3]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
indices_de_condicion = arr > 5 #Retorna booleanos
indices_de_condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

¿Qué pasa si quiero aplicarla a arr?

In [8]:
arr[indices_de_condicion] #Solo retorna las condiciones TRUE. Es lo mismo que hacer arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
arr[indices_de_condicion & (arr < 9)] 

array([6, 7, 8], dtype=int8)

In [12]:
arr[indices_de_condicion] = 99

In [13]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [14]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)

De los comentarios en Platzi

In [15]:
np.where(arr > 3) #Arroja los indices que cumplen la condición

(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)