In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

Supongamos que a ese slice de arr le quiero hacer algunos cambios

In [7]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

Ahora si volvemos al array original vemos un problema

In [8]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Para evitar esta destrucción lo que se hace es una copia con $copy$

In [15]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 100

In [17]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Y el array original es respetado

In [18]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])