In [1]:
import numpy as np

In [2]:
list(range(0,10)) #Creando una lista en python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10) #Creando un array en python con numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20,2) #Puede darle el step 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros(3) #Para crear un esquema previo

array([0., 0., 0.])

In [6]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,10,100) #El último es el número de datos

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [11]:
np.eye(4) #Matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand() #valor aleatorio entre 0 y 1

0.7614535439568846

In [14]:
np.random.rand(4)

array([0.01379862, 0.32335502, 0.51586885, 0.30268154])

In [16]:
np.random.rand(4,4)

array([[0.98498588, 0.96624602, 0.57790143, 0.77784521],
       [0.99042787, 0.04402701, 0.2461929 , 0.64182314],
       [0.27594682, 0.29769566, 0.20277193, 0.83334492],
       [0.64054336, 0.02276485, 0.72661982, 0.35663808]])

In [19]:
np.random.randint(1,15) #Número entero aleatorio

7

In [20]:
np.random.randint(1,100, (10,10)) #Se le puede añadir la estructura

array([[90, 87, 79,  4,  5, 77, 48, 35, 22, 94],
       [53, 72, 80, 93, 17, 18, 47,  4, 85, 73],
       [48, 58, 41, 66, 36, 31, 65, 86, 36, 59],
       [ 6, 72, 25, 44, 19,  5, 62, 58, 39, 25],
       [80, 33, 33, 14, 72, 51, 98, 91, 21,  9],
       [33, 27, 68,  7, 77, 52, 86, 48, 87, 36],
       [90, 25, 64, 66, 34, 18, 46, 89, 63, 54],
       [40, 98, 55, 35, 73, 31, 63, 85, 44, 16],
       [99,  2, 99, 21, 87, 43, 43, 34,  2,  7],
       [66, 87, 35, 24, 24, 89, 91, 35, 51,  3]])