In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)
arr

array([ 3, 16,  5, 11, 15,  9,  1,  5, 16,  9])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 3, 16,  5, 11, 15],
       [ 9,  1,  5, 16,  9]])

In [7]:
matriz.max() #El valor más grande del array

16

In [8]:
matriz.max(1) #El valor más grande del array por filas

array([16, 16])

In [10]:
matriz.max(0) #El valor más grande del array por columnas

array([ 9, 16,  5, 16, 15])

In [14]:
print(arr)
arr.argmax() #índice del valor máximo del array

[ 3 16  5 11 15  9  1  5 16  9]


1

In [16]:
print(matriz)
matriz.argmax(0)

[[ 3 16  5 11 15]
 [ 9  1  5 16  9]]


array([1, 0, 0, 1, 0], dtype=int64)

In [17]:
arr.min() #Devuelve el valor mínimo

1

In [18]:
arr

array([ 3, 16,  5, 11, 15,  9,  1,  5, 16,  9])

In [19]:
arr.ptp() #Peak to peak, cuántos números hay entre el mínimo y el máximo

15

In [24]:
matriz

array([[ 3, 16,  5, 11, 15],
       [ 9,  1,  5, 16,  9]])

In [23]:
print(matriz.ptp())
print(matriz.ptp(0))
print(matriz.ptp(1))

15
[ 6 15  0  5  6]
[13 15]


In [28]:
np.percentile(arr,50) #Regresa el valor de enmedio si se orden de menor a meyor

9.0

In [31]:
arr.sort() #Los ordena de menor a mayor, así puedes comprobar el percentil
arr

array([ 1,  3,  5,  5,  9,  9, 11, 15, 16, 16])

In [32]:
np.median(arr) #Mediana

9.0

In [35]:
np.median(matriz,0)

array([ 5. ,  7. , 10. , 10.5, 12.5])

In [39]:
np.std(arr) #desviación estándar

5.196152422706632

In [40]:
np.var(arr) #Varianza

27.0

In [41]:
np.mean(arr)

9.0

In [42]:
np.mean(matriz,0)

array([ 5. ,  7. , 10. , 10.5, 12.5])

In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [47]:
np.concatenate((a,b),axis = 1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [48]:
b = np.expand_dims(b,axis = 0)

In [49]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.concatenate((a,b),axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [53]:
np.concatenate((a,b.T),axis = 1) #La T indica la transpuesta

array([[1, 2, 5],
       [3, 4, 6]])