In [1]:
import numpy as np

In [2]:
lista = [1 ,2]
lista

[1, 2]

In [3]:
#Multiplicando los valores de la lista
lista * 2

[1, 2, 1, 2]

Salió mal y es poco eficiente

In [6]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Multiplicación de cada uno de los valores

In [7]:
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Suma a cada uno de los valores

In [9]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Division entre cada uno de los valores

In [10]:
1/arr2

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_12192/1672552411.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Potencia

In [11]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

Operaciones netre arrays

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Ahora con una matriz

In [16]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [17]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Producto punto de 2 MANERAS

In [22]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [23]:
matriz @matriz2.T

array([[ 30,  80],
       [ 80, 255]])