In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[2, 7],
       [9, 5],
       [7, 3]])

In [4]:
arr.shape #dice cuantas filas y columnas tengo, en tensores da las dimensiones

(3, 2)

In [5]:
arr

array([[2, 7],
       [9, 5],
       [7, 3]])

In [7]:
arr.reshape(1,6) #Hace válido el cambio de forma de un array establecido

array([[2, 7, 9, 5, 7, 3]])

In [8]:
arr.reshape(2,3)

array([[2, 7, 9],
       [5, 7, 3]])

In [10]:
np.reshape(arr,(1,6)) #Otra forma de aplicarlo

array([[2, 7, 9, 5, 7, 3]])

In [11]:
arr

array([[2, 7],
       [9, 5],
       [7, 3]])

In [12]:
np.reshape(arr,(2,3),'C') #Le digo que lo reordene pero como lo hace el lenguaje c

array([[2, 7, 9],
       [5, 7, 3]])

In [13]:
np.reshape(arr,(2,3),'F') #Le digo que lo reordene pero como lo hace el lenguaje FORTRAND

array([[2, 7, 5],
       [9, 7, 3]])

In [14]:
np.reshape(arr,(2,3),'A') #Le digo que lo reordene pero como lo haría mi sistema. Esto ahorra tiempo

array([[2, 7, 9],
       [5, 7, 3]])

Reto, creando un tensor y haciendo shape y reshape

In [19]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
tensor

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
tensor.reshape(2,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
tensor.reshape(1,18)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
tensor.reshape(3,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3],
       [4, 5, 6, 7, 8, 9]])